import parse from 'html-react-parser'

const WP_GRAPHQL = 'https://hq.funkmedia.net/ujamaaexpo/graphql'

async function getHomePage() {
  const settingsRes = await fetch(WP_GRAPHQL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      query: `{
        allSettings {
          readingSettingsShowOnFront
          readingSettingsPageOnFront
        }
      }`,
    }),
    next: { revalidate: 60 },
  })
  const settings = await settingsRes.json()
  const pageId = settings?.data?.allSettings?.readingSettingsPageOnFront
  if (!pageId) return null

  const pageRes = await fetch(WP_GRAPHQL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      query: `query GetHome($id: ID!) {
        page(id: $id, idType: DATABASE_ID) {
          title
          postBlockSupportStyles
          editorBlocks(flat: true) {
            __typename
            renderedHtml
            clientId
            parentClientId
          }
        }
      }`,
      variables: { id: String(pageId) },
    }),
    next: { revalidate: 60 },
  })
  const page = await pageRes.json()
  return page?.data?.page
}

async function getThemeCSS() {
  const res = await fetch(
    'https://hq.funkmedia.net/ujamaaexpo/wp-json/fm-styles/v1/theme.css',
    { next: { revalidate: 3600 } }
  )
  const raw = await res.text()
  try {
    const parsed = JSON.parse(raw)
    return typeof parsed === 'string' ? parsed : raw
  } catch {
    return raw
  }
}

export default async function HomePage() {
  const [page, themeCSS] = await Promise.all([getHomePage(), getThemeCSS()])

  if (!page) {
    return <div className="flex items-center justify-center min-h-screen text-white bg-black">Loading...</div>
  }

  const blocks = (page.editorBlocks || []).filter((b: any) => !b.parentClientId)

  return (
    <>
      {/* SECURITY: Theme CSS is compiled by wp_get_global_stylesheet() on our WP server.
          postBlockSupportStyles is generated by WordPress block rendering engine.
          Both contain only CSS declarations — no HTML or user-supplied content. */}
      <style id="wp-global-styles">{themeCSS}</style>
      {page.postBlockSupportStyles && (
        <style id="wp-post-styles">{page.postBlockSupportStyles}</style>
      )}

      <div className="wp-site-blocks is-layout-constrained">
        {blocks.map((block: any) => {
          const html = block?.renderedHtml || ''
          if (!html) return null
          return <div key={block.clientId}>{parse(html)}</div>
        })}
      </div>
    </>
  )
}
